- Swifter/Swifter.swift
- Swifter/SwifterHTTPRequest.swift
Defer `JSON.parseJSONData` to background thread, so that large chunk of JSON data won't block main thread.
I encountered this main thread lagging issue when requesting 154 friends data from API. Instruments showed time spending in JSON parsing is huge. With this commit, background thread usage increased with a meaningful amount.
> JSON parsing performance

- Swifter/SwifterFavorites.swift
- Swifter/SwifterFollowers.swift
- Swifter/SwifterUsers.swift
There was a corresponding leakage. :disappointed_relieved: #60
> Replaced all `id: Int` with `id: String` ( There was a corresponding leakage )

- Swifter/JSON.swift
jsonValue["some_attribute"].boolValue is always true.
> Fix bool value.

- SwifterDemoiOS/AuthViewController.swift
failureHandler on line 85 in the Auth controller in the Demo referes to an inaccessable method causing a build error. Now it simply alerts the error.
> patched failureHandler build error 

- Swifter/SwifterLists.swift
When trying to use `getListsOwnershipsWithUserID` I was getting this error 
`HTTP Status 400: Bad Request, Response: {"errors":[{"code":86,"message":"This method requires a GET or HEAD."}]}`
Digging in, I found that `getListsOwnershipsWithUserID` was using a POST request rather than a GET.
> getListsOwnershipsWithUserID was using a POST request rather than a GET

- Swifter/SwifterFollowers.swift
Minor change to use `Dictionary<String, Any>` instead of `Dictionary<String, AnyObject>` for the parameters in the SwifterFollowers endpoints. This seems to be the case in all the other API functions, and I had to make that change for the functions to work.
> AnyObject -> Any on SwifterFollowers.swift endpoints

- Swifter/SwifterStreaming.swift
As written in the [Twitter Documentation](https://dev.twitter.com/streaming/overview/request-parameters#with):
>The *with* parameter controls the types of messages delivered to User and Site Streams clients. 
>
>* The default for User Streams is *with=followings* which adds messages from accounts the user follows, equivalent to the user’s home timeline.
In conclusion, for User Streams:
* *with* = "user" to stream only messages from the user (associated with the stream);
* *with* = "following" to stream also messages from accounts the user (associated with the stream) follows;
Before this fix, the function *getUserStreamDelimited* was doing exactly the opposite of what it promised.
> fixed getUserStreamDelimited parameter

- Swifter.xcodeproj/project.pbxproj
- Swifter/Operator+Swifter.swift
- Swifter/String+Swifter.swift
- Swifter/SwifterAppOnlyClient.swift
- Swifter/SwifterFavorites.swift
- Swifter/SwifterFollowers.swift
- Swifter/SwifterHTTPRequest.swift
- Swifter/SwifterHelp.swift
- Swifter/SwifterLists.swift
- Swifter/SwifterMessages.swift
- Swifter/SwifterOAuthClient.swift
- Swifter/SwifterPlaces.swift
- Swifter/SwifterSearch.swift
- Swifter/SwifterStreaming.swift
- Swifter/SwifterSuggested.swift
- Swifter/SwifterTimelines.swift
- Swifter/SwifterTrends.swift
- Swifter/SwifterTweets.swift
- Swifter/SwifterUsers.swift
- SwifterDemoiOS/AuthViewController.swift
When setting the parameters, we currently use...
```
if variable != nil {
parameters[key] = variable!
}
``` 
...which becomes rather redundant and repetitive after a while; so instead, I added a `??=` operator which checks if the `rhs` is not a nil, if so, it'll set the value of `rhs` to `lhs` (aka parameter[key])
> Replace `if variable != nil {}` with ??= operator

- Swifter/SwifterAuth.swift
- SwifterDemoMac/Base.lproj/Main.storyboard
Fixed #125 by creating 2 separate methods for authorizeWithCallbackURL: 
One with `#if os(OSX)` and another with `#if os(iOS)`
> Fix Mac Demo failing due to UIViewController parameter

- Swifter/Dictionary+Swifter.swift
- Swifter/String+Swifter.swift
If "[]" are not escaped,  Dictionary<String, String> cannot be posted via Swifter instance as below.
```
let swifter = Swifter(consumerKey: TWITTER_CONSUMER_KEY, consumerSecret: TWITTER_CONSUMER_SECRET, oauthToken: TWITTER_ACCESS_TOKEN, oauthTokenSecret: TWITTER_ACCESS_TOKEN_SECRET)
let text = {"date" : NSDate().description}.description
swifter.postStatusUpdate(text, success: { status in
}, failure: { error in
debugPrint(error)
})
```
then, HTTP status code 401 is returned from Twitter.
> Remove [] from allowed characters of urlEncodings.

- Swifter.xcodeproj/project.pbxproj
- Swifter/Swifter.swift
- Swifter/SwifterAuth.swift
- Swifter/SwifterFavorites.swift
- Swifter/SwifterFollowers.swift
- Swifter/SwifterHelp.swift
- Swifter/SwifterLists.swift
- Swifter/SwifterMessages.swift
- Swifter/SwifterOAuthClient.swift
- Swifter/SwifterPlaces.swift
- Swifter/SwifterSavedSearches.swift
- Swifter/SwifterSearch.swift
- Swifter/SwifterSpam.swift
- Swifter/SwifterStreaming.swift
- Swifter/SwifterSuggested.swift
- Swifter/SwifterTag.swift
- Swifter/SwifterTimelines.swift
- Swifter/SwifterTrends.swift
- Swifter/SwifterTweets.swift
- Swifter/SwifterUsers.swift
Thought I'd open a pull request to explain what I did.
In Swifter, wherever there is a method with both `screenName` OR `userId` options, Swifter offers 2 methods for users using either or. But sometimes people get confused with them, and it's not that great to have a lot of duplicated code.
So... I thought of a solution and implemented it today.
Now, there is a new `enum UserTag` that basically has 2 cases: `.id(String)` and `.screenName(String)`
How does this work exactly? Suppose you want to fetch a list of your favourited tweets. Previously, you had to choose between the two methods, and sometimes we make a mistake and mix the 2 up.
```swift
func getFavoritesList(withId userID: String, count: Int? = nil, sinceID: String? = nil, maxID: String? = nil, success: ((statuses: [JSON]?) -> …
```
> Use Tag enums for User (id/screenName) and List (id/slug) 

- Swifter/SwifterTweets.swift
The added parameter "additionalOwners" is corresponding to the optional
parameter "addtional_owners" in the twitter's document, which is a
comma-separated list of user IDs to set as additional owners allowed to
use the returned media_id in Tweets or Cards. Up to 100 additional
owners may be specified.
This parameter will be useful when someone wants to post a media tweet
by multiple twitter accounts at one time without having to uploading
the media for multiple times, which is a waste of networking.
I forked it just because I came across the problem to give some ownership of the media to reuse it. I spent hours to learn about the twitter's document and found it's really convenient to post a tweet with your awesome project, which is just lack of a parameter I need. 
Maybe few people have …
> Added a function with an extra parameter to use the "addtional_owners" in twitter's API

- Sources/Swifter.h
- Swifter.xcodeproj/project.pbxproj
- SwifterDemoiOS/Images.xcassets/AppIcon.appiconset/Contents.json
Added `#import "Swifter-Swift.h"` in `Swifter.h` so CocoaPods could index other Swift files. Without this, CocoaPods could not find `Swifter.swift`. You'll need to bump the CocoaPods version number and send out a new release. :-)
> Add #import statement for Swift code

- Sources/SwifterMessages.swift
> fix typo. destoryDirectMessage => destroyDirectMessage

- Sources/SwifterHTTPRequest.swift
`URLSession` holds a strong reference to its delegate, and only releases
that reference in a call to `finishTasksAndInvalidate()`. We need to call
it inside `HTTPRequest.urlSession(_:task:didCompleteWithError)`.
Before & After (in the Leaks instrument):
> Fix leak in HTTPRequest.start()

- Sources/SwifterLists.swift
- Sources/SwifterTimelines.swift
- Sources/SwifterUsers.swift
Fixes typos in the names of a handful of functions across SwifterLists.swift, SwifterTimelines.swift and SwifterUsers.swift.
> Fix a number of typos in the public API

- Sources/SwifterTweets.swift
Fix `public func UnretweetTweet(...)` to `public func unretweetTweet(...)`.
> Fix a upper-camelcase

- Sources/SwifterLists.swift
Hello @mattdonnelly 😺
I added `count` parameter to `getListMemberships()`
[Official API Reference]
https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-memberships
> Add 'count' parameter to getListMemberships()

- Sources/JSON.swift
I found the bug in JSON.prettyPrint method when including newline or quote in string
I fixed it, so please check it!
Regards,
> Fix JSON.prettyPrint generates invalid JSON

- Sources/Swifter.swift
- Sources/SwifterFavorites.swift
- Sources/SwifterLists.swift
- Sources/SwifterSearch.swift
- Sources/SwifterTimelines.swift
- Sources/SwifterTweets.swift
Adding the tweet_mode parameter to functions that return tweets allows for specifying the "extended" tweet mode, which is how Twitter delivers the new longer tweets without truncating them. It will also allow for specifying "compat" mode when extended becomes the default.
> Add tweet mode parameter to relevant functions

- Sources/Swifter.swift
- Sources/SwifterAccountsClient.swift
- Sources/SwifterGIF.swift
- Sources/SwifterHTTPRequest.swift
- Sources/SwifterOAuthClient.swift
- Swifter.xcodeproj/project.pbxproj
These changes address the problems mentioned in #192.
Don't fail on an empty response with a 2xx status code, such as during a chunked media upload.
Fix the multipart form data issue causing chunked uploads to fail with a Twitter error on "FINALIZE".
Address a couple of String(describing:) issues with optional strings.
Fix a bug in OAuth and Accounts clients that fail to remove the fileNameKey from the parameters dictionary.
Added a simple tweetGIF method to post a tweet with an animated gif attached.
> Media upload improvements

- Sources/SwifterTimelines.swift
I needed more customisation of the timeline parameters so I created a straight forward helper method here that passes params directly to the `getJSON` method. 👊
> Adding custom timeline method for manual parameter entry

- Sources/SwifterAuth.swift
- Sources/SwifterUsers.swift
I added support to get the user email if you have the right permissions with `include_email ` parameter.
Also added support for a custom `SFSafariViewControllerDelegate ` in case you don't what your view controller to handle it if this is not set it uses the view controller as it was before.
Removed the` #available(iOS 9.0, *)` because the minimum deploy target is already iOS9 so I don't think there is a need to check for it.
Updated the prevent animation to match the one used by other social logins (Facebook and Google)
If you think that some of these do not make sense I can remove them.
> Added support for getting email & more

- Sources/JSON.swift
- Swifter.xcodeproj/project.pbxproj
- Tests/SwifterTests/JSONTest.swift
Hi! 😄  
I'm using Swifter like following.
```swift
// let json = ... // A JSON instance from Swifter.
let jsonStr = String(describing: json)
// some thing...
let jsonData = jsonStr.data(using: .utf8)
let object = try JSONSerialization.jsonObject(with: jsonData, options: []) // <- An error occurred.
```
But I got the following error. :cry:
`"Error Domain=NSCocoaErrorDomain Code=3840 "Invalid escape sequence around character 39." UserInfo={NSDebugDescription=Invalid escape sequence around character 39.}"`
I thought that strings made from JSON instances should be convertible to JSON.
So I fixed it to be that way.
> Fix pretty print json

- Package.swift
- Sources/Scanner++.swift
I tried building Swifter on Linux (Raspbian) with Swift 4.2 (https://ko-fi.com/post/Swift-4-2-Binaries-F1F6KMBY) and SPM but the build would always fail with this error:
```
String++.swift:65:35: error: extraneous argument label 'string:' in call
_ = scanner.scanString(string: "=")
```
I managed to get it working by slightly changing the `Scanner` extensions, specifically by making the `scanString(string:)` method available on Linux.
I am, however, not sure if this change would break something in a different build environment.
> Building with Swift 4.2 on Linux

- Sources/SwifterError.swift
The current SwifterError is not a LocalizedError and calling localizedDescription does not return the expected description.
> Make SwifterError a LocalizedError

- Sources/SwifterUsers.swift
Dear swifter developers.
Hello. Now I create my homebrew twitter client and get my profile banner & images.
I called "getProfileBanner" function when got a "Method not allowed(405)" error.
this function uses the "POST" method. Maybe correct is the "GET" method.
https://developer.twitter.com/en/docs/accounts-and-users/user-profile-images-and-banners.html
Please review my code.
Thx!
> Fixed getProfileBanner error.

- Sources/SwifterTweets.swift
"additional_owers" to "additional_owners"
Maybe it is correct in the Twitter API Document.
https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload
Please check this PR. Thx.
> Fix key misspelling

- Sources/Swifter.swift
- Sources/SwifterAuth.swift
This is a more proper way removing block based listeners.  `NotificationCenter.default.removeObserver(self)` does nothing.
> Resolved issue causing multiple listeners to remain active

- README.md
SSO was port from twitter-kit.
So, Twitter may think deprecate sso.
I think that Swifter also should documented this.
> SSO was deprecated.

- Sources/SwifterHelp.swift
The rate limit API can get all categories without specifying "resources" in the parameter.
 Could not get all categories even if you specify an empty array in [String] ().
So "resources" should be optional.
> Get all categories.

- Sources/SwifterHelp.swift
In the commit [23db8e0](https://github.com/mattdonnelly/Swifter/commit/23db8e0ece26b02de9c94dbc5bca1a5710470322) that becomes to allow you to call the function `getRateLimits` without setting parameter `resources`, an empty array will be assigned in default.
On this state, the error it will be occurred in line 104.
To solve this, rewrite `resources .joined (...)` with `resources? .joined (...)`.
> Fix unwrapped variable "resources"s handling
